/*******************************************************************************
* Title                 :   atmega4808_rtc Component   
* Filename              :   atmega4808_rtc.c
* Author                :   Quang Hai Nguyen
* Origin Date           :   22.04.2020
* Version               :   0.0.99
*
*******************************************************************************/

/*************** SOURCE REVISION LOG *****************************************
*
*  Date         Version     Author              Description 
*  22.04.2020   0.0.99       Quang Hai Nguyen    Initial Release.
*
*******************************************************************************/
/** @file  atmega4808_rtc.c
 *  @brief This is the source file for atmega4808_rtc component
 */

/******************************************************************************
* Includes
*******************************************************************************/
#include "atmega4808_rtc.h"

/******************************************************************************
* Module Typedefs
*******************************************************************************/
//None

/******************************************************************************
* Module Variable Definitions
*******************************************************************************/
/** \brief store the tick value */
volatile static uint32_t tick = 0;

/******************************************************************************
* Function Definitions
*******************************************************************************/

/******************************************************************************
* Function : ATMEGA4808_RTC_Init
*//** 
* \b Description:
*
* This function initializes RTC peripheral, set the period of the RTC and enable
* overflow interrupt 
*
* PRE-CONDITION: RTC must be generated by MCC or manually implemented  
*
* POST-CONDITION: None
* 
* @param    None
* @return   None
*
* \b Example Example:
* @code
* 	ATMEGA4808_RTC_Init();
* @endcode
*
* @see ATMEGA4808_RTC_Init
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 22.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
void ATMEGA4808_RTC_Init(void)
{
#if RTC_PERIOD > 0xFFFF
#warining RTC period must be 16-bit
#endif
    ATMEGA4808_RTC_Stop();
     while (RTC.STATUS > 0) { /* Wait for all register to be synchronized */
    }
    RTC.INTCTRL |= RTC_OVF_bm; 
    RTC.PER = RTC_PERIOD;
    tick = 0;
}

/******************************************************************************
* Function : ATMEGA4808_RTC_DeInit
*//** 
* \b Description:
*
* This function de-initializes RTC peripheral
*
* PRE-CONDITION: RTC must be generated by MCC or manually implemented  
*
* POST-CONDITION: None
* data
* @param    None
* @return   None
*
* \b Example Example:
* @code
* 	ATMEGA4808_RTC_DeInit();
* @endcode
*
* @see ATMEGA4808_RTC_DeInit
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 22.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
void ATMEGA4808_RTC_DeInit(void)
{
    ATMEGA4808_RTC_Stop();
    
    //disable RTC overflow interrupt
    RTC.INTCTRL &= ~RTC_OVF_bm;
    
    //reset tick
    tick = 0;
}

/******************************************************************************
* Function : ATMEGA4808_RTC_Start
*//** 
* \b Description:
*
* This function starts the RTC timer
*
* PRE-CONDITION: RTC must be initialized 
*
* POST-CONDITION: None
* data
* @param    None
* @return   None
*
* \b Example Example:
* @code
* 	ATMEGA4808_RTC_Start();
* @endcode
*
* @see ATMEGA4808_RTC_Init
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 22.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
void ATMEGA4808_RTC_Start(void)
{
    RTC.CTRLA |= (1 << RTC_RTCEN_bp) ;
}

/******************************************************************************
* Function : ATMEGA4808_RTC_Stop
*//** 
* \b Description:
*
* This function stops the RTC timer
*
* PRE-CONDITION: RTC must be initialized 
*
* POST-CONDITION: None
* data
* @param    None
* @return   None
*
* \b Example Example:
* @code
* 	ATMEGA4808_RTC_Stop();
* @endcode
*
* @see ATMEGA4808_RTC_Init
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 22.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
void ATMEGA4808_RTC_Stop(void)
{
    RTC.CTRLA &= ~(1 << RTC_RTCEN_bp) ;
}

/******************************************************************************
* Function : ATMEGA4808_RTC_GetTicks
*//** 
* \b Description:
*
* This function return the current tick of the RTC
*
* PRE-CONDITION: RTC must be initialized (and started)
*
* POST-CONDITION: None
* data
* @param    None
* @return   current tick value
*
* \b Example Example:
* @code
*   uint32_t tick = 0;
*   ATMEGA4808_RTC_Init(); 
*   ATMEGA4808_RTC_Start();
* 	tick = ATMEGA4808_RTC_GetTicks();
* @endcode
*
* @see ATMEGA4808_RTC_Init
* @see ATMEGA4808_RTC_Start
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 22.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
uint32_t ATMEGA4808_RTC_GetTicks(void)
{
    return tick;
}

/******************************************************************************
* Function : ATMEGA4808_RTC_SetTicks
*//** 
* \b Description:
*
* This function sets the tick of the RTC to new value
*
* PRE-CONDITION: RTC must be initialized
*
* POST-CONDITION: None
* data
* @param    new_tick(IN): new tick value
* @return   None
*
* \b Example Example:
* @code
*   ATMEGA4808_RTC_Init(); 
*   ATMEGA4808_RTC_Start();
* 	ATMEGA4808_RTC_SetTicks(1000);
* @endcode
*
* @see ATMEGA4808_RTC_Init
* @see ATMEGA4808_RTC_Start
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 22.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
void ATMEGA4808_RTC_SetTicks(uint32_t new_tick)
{
    tick = new_tick;
}

/******************************************************************************
* Function : ISR(RTC_CNT_vect)
*//** 
* \b Description:
*
* Interrupt service routine of the RTC overflow interrupt
*
* PRE-CONDITION: RTC must be initialized
*
* POST-CONDITION: None
* data
* @param    None
* @return   None
*
* @see ATMEGA4808_RTC_Init
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 22.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
ISR(RTC_CNT_vect)
{
    if (RTC.INTFLAGS & RTC_OVF_bm ){
        ++tick; //
    }  
    RTC.INTFLAGS = RTC_OVF_bm;
}