/*******************************************************************************
* Title                 :   atmega4808_pwm Component   
* Filename              :   atmega4808_pwm.c
* Author                :   Quang Hai Nguyen
* Origin Date           :   20.04.2020
* Version               :   0.0.99
*
*******************************************************************************/

/*************** SOURCE REVISION LOG *****************************************
*
*  Date         Version     Author              Description 
*  20.04.2020   1.0.0       Quang Hai Nguyen    Initial Release.
*
*******************************************************************************/
/** @file  atmega4808_pwm.c
 *  @brief This is the source file for atmega4808_pwm component
 */
#define     DEGREE_TO_NANO_SEC(x)           (1000000 + (x * 5556))
/******************************************************************************
* Includes
*******************************************************************************/
#include "servo.h"
#include "atmega4808_pwm.h"

/******************************************************************************
* Module Typedefs
*******************************************************************************/


/******************************************************************************
* Module Variable Definitions
*******************************************************************************/


/******************************************************************************
* Function Definitions
*******************************************************************************/


/******************************************************************************
* Function : ATMEGA4808_PWM_Init
*//** 
* \b Description:
*
* This function initializes the TCA of the Atmega4808 and uses it as single
* slope PWM generator. The initialization is actually carried out by Microchip 
* Code Configurator (MCC), we only modify minor detail.
*
* PRE-CONDITION: TCA must be generated by MCC or manually implemented  
*
* POST-CONDITION: None
* data
* @param    None
* @return   None
*
* \b Example Example:
* @code
* 	ATMEGA4808_PWM_Init();
* @endcode
*
* @see ATMEGA4808_PWM_Init
*
* <br><b> - HISTORY OF CHANGES - </b>
*  
* <table align="left" style="width:800px">
* <tr><td> Date       </td><td> Software Version </td><td> Initials         </td><td> Description </td></tr>
* <tr><td> 20.04.2020 </td><td> 0.0.99           </td><td> Quang Hai Nguyen </td><td> Interface Created </td></tr>
* </table><br><br>
* <hr>
*
*******************************************************************************/
void ServoInit(void)
{
    
    ATMEGA4808_PWM_Init();
    ATMEGA4808_PWM_SetPeriod(20000000);
}

void ServoSetPosition(uint16_t u16DestinationDegree)
{
    uint32_t u32NanoSec; 
    u32NanoSec = 1000000 + (u16DestinationDegree * 5556);
    ATMEGA4808_PWM_SetDutyCycle(u32NanoSec);
}

void ServoStop(void)
{
    ATMEGA4808_PWM_Stop();
}

void ServoStart(void)
{
    ATMEGA4808_PWM_Start();
}


/*** End of File **************************************************************/